services:
  vaultwarden:
    image: vaultwarden/server:latest
    pull_policy: always
    restart: always
    environment:
      - DOMAIN=${DOMAIN}
      - ADMIN_TOKEN=${VAULTWARDEN_ADMIN_TOKEN}
      - ADMIN_RATELIMIT_SECONDS=${ADMIN_RATELIMIT_SECONDS}
      - SIGNUPS_ALLOWED=${SIGNUPS_ALLOWED}
    volumes:
      - vaultwarden-data:/data
    ports:
      - 11001
      - 80

volumes:
  vaultwarden-data: